### ISSUE TITLE
bug: Next.js + SSR components - 'ReferenceError: Node is not defined'

### ISSUE THREAD

**Issue by guilhermebc** [ionic-team/stencil-ds-output-targets#479]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.21.0

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.7.1

### Current Behavior

Hello, I work at a company where we use Stencil for the internal design system and export it to React, as we have projects in Next.js (^14.2.3).

We use version ^0.5.3 of the @stencil/react-output-target package for using the components in Next.js projects and were waiting for the launch of SSR support.

As soon as the SSR components support was released for react-output-target, I went to test updating it in the company's design system, but I am not able to compile the application, I followed all the steps in the Stencil documentation.

Our design system is published in a private repository manager, and we install it in the company's applications (Vue apps, Next.js apps, etc).

Error:
```bash
➜  nextjs-with-stencil-ssr git:(main) ✗ 
yarn build
yarn build
yarn run v1.22.22
$ next build
  ▲ Next.js 14.2.11

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/5)  [=   ]ReferenceError: Node is not defined
    at ta (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:85335)
    at e6 (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:83143)
    at td (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:86752)
    at 4978 (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:91142)
    at Object.t [as require] (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/webpack-runtime.js:1:128)
    at require (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18224)
    at I (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
    at C (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
    at rP (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
    at nN (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304) {
  digest: '1355879404'
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: Node is not defined
    at ta (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:85335)
    at e6 (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:83143)
    at td (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:86752)
    at 4978 (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/app/page.js:1:91142)
    at Object.t [as require] (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/.next/server/webpack-runtime.js:1:128)
    at require (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18224)
    at I (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
    at C (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
    at rP (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
    at nN (/Users/guilherme.costa/workspace/nextjs-with-stencil-ssr/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304)
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /page: /
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Setup Next.js app router + SSR + Stencil react output target components.server working

### Steps to Reproduce

In separate repositories, create a design system (design-system-web-components) in Stencil (^4.21.0)

## design-system-web-components
```
 yarn create stencil
```

Setup the react-output-target (^0.7.1) para ssr:
`stencil.config.ts` of `design-system-web-components`
```
...
outputTargets: [
    reactOutputTarget({
      outDir: '../nextjs-output-target/src/',
      hydrateModule: 'design-system/hydrate'
    }),
    {
      type: 'dist-custom-elements',
      externalRuntime: false,
    },
    {
      type: 'dist-hydrate-script',
      dir: './hydrate',
    },
]
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "jsx": "react",
    "jsxFactory": "h"
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

<hr>

## design-system-nextjs
`package.json`
```json
{
  "name": "design-system-nextjs",
  "version": "1.0.0",
  "type": "module",
  "main": "src/index.js",
  "module": "src/index.js",
  "types": "src/index.d.ts",
  "dependencies": {
    "design-system-web-components": "0.0.1",
    "@stencil/react-output-target": "^0.7.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "react": "^18",
    "react-dom": "^18",
    "typescript": "^5"
  }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "outDir": "./dist",
    "lib": ["dom", "es2015"],
    "module": "esnext",
    "moduleResolution": "bundler",
    "target": "es2015",
    "skipLibCheck": true,
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "declarationDir": "./dist",
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}

```

Follow all the documentation: [https://stenciljs.com/docs/react](vscode-file://vscode-app/private/var/folders/bk/dx9465yd58s5glx2mhw9rq6w0000gq/T/AppTranslocation/54317DC8-4FA6-496F-9994-4104A339363F/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html); Publish the design-system-web-components and design-system-nextjs libraries;

In another repository, create the Next.js application following the standard with App router, TypeScript, ESLint:
```
npx create-next-app@latest
```

Install the design-system-nextjs library;
Import a component from the library in app/page.tsx;
Run `next build` or `next dev` commands and the error will appear.

### Code Reproduction URL

-

### Additional Information

<img width="1789" alt="Screenshot 2024-09-12 at 23 16 23" src="https://github.com/user-attachments/assets/9908e5e0-e788-44ff-afe6-ff6ce6700c97">

**Comment by guilhermebc** [comment]
Hey @christian-bromann 

Design system repo: https://github.com/guilhermebc/gbc-design-system
Nextjs app + design system repo: https://github.com/guilhermebc/nextjs-with-stencil-ssr

The version `@guilhermebc/gbc-design-system-nextjs@1.0.8` is causing the error.

I ended up discovering that the cause of the error is coming from the extra settings we need to apply for slot correction:
`stencil.config.ts`
```
extras: {
    enableImportInjection: true,
    experimentalSlotFixes: true,
    scopedSlotTextContentFix: true,
}
```

I generated a version `@guilhermebc/gbc-design-system-nextjs@1.0.9` removing these extra settings and the error does not occur, but in any case, we need these settings applied in our internal design system.

To reproduce, just download the repository https://github.com/guilhermebc/nextjs-with-stencil-ssr:
 1 - Install the dependencies `yarn install`
 2 - Run build with `yarn build`

PS: To simulate without the error, just install the version `@guilhermebc/gbc-design-system-nextjs@1.0.9`

Preview: 
![Screenshot 2024-09-26 at 10 15 51](https://github.com/user-attachments/assets/3639866b-dc95-4913-b580-f017b9662001)
